---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "05"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # email: mail@example.com # Replace with your email
    # skipTLSVerify: true
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - dns01:
        route53:
          accessKeyIDSecretRef:
            name: aws-creds
            key: aws_access_key_id
          region: "{{ .Values.route53.region }}"
          secretAccessKeySecretRef:
            name: aws-creds
            key: aws_secret_access_key
