---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-dynamic
  namespace: test-secrets
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:

  # Mount path where the KV engine is enabled in Vault
  mount: secret

  # Path of the secret in Vault
  path: demo1

  # Specify destination details for Kubernetes secret creation
  destination:
    name: vso-dynamic
    create: true

  # # Restart these pods when secrets rotated
  # rolloutRestartTargets:
  # - kind: Deployment
  #   name: vso-db-demo

  # Interval to refresh the static secret (ensure this matches operational requirements)
  refreshAfter: 30s

  # Name of the Vault authentication reference
  vaultAuthRef: static-auth
