---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: vso-pki
  namespace: test-secrets
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  vaultAuthRef: vault-auth
  mount: pki
  role: example-dot-com # Related to Server config
  commonName: www.my-website.com # Related to Server config
  format: pem
  # Triggers certificate renewal 20 seconds before expiration
  expiryOffset: 20s
  # Certificate validity period
  ttl: 60s
  # namespace: tenant-1
  destination:
    create: true
    name: vso-pki
