---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: avp-example
  name: avp-example
  namespace: avp-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-secrets
  project: default
  source:
    path: 09-argocd-vault-plugin-example
    repoURL: https://github.com/alvarolop/ocp-secured-integration.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
