---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: vault-secrets-operator
  name: vault-secrets-operator
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 07-vault-secrets-operator
    repoURL: https://github.com/alvarolop/ocp-secured-integration.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
