---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: secrets-store-csi-driver
  name: secrets-store-csi-driver
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: 06-secrets-store-csi-driver
    repoURL: https://github.com/alvarolop/ocp-secured-integration.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
