---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: eso-operator
  name: eso-operator
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets # Namespace where ESO will be installed
  project: default
  source:
    repoURL: https://charts.external-secrets.io # ESO Helm chart repository
    targetRevision: 0.12.1 # Specify the desired version of the Helm chart
    chart: external-secrets # Name of the ESO Helm chart
    helm:
      values: | 
        installCRDs: true # Ensures that CRDs are installed with the chart
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: eso-config
  name: eso-config
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-secrets
  project: default
  source:
    path: 08-external-secrets-operator
    repoURL: https://github.com/alvarolop/ocp-secured-integration.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
