---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: external-secrets-operator
  name: external-secrets-operator
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-secrets
  project: default
  source:
    path: 08-external-secrets-operator
    repoURL: https://github.com/alvarolop/ocp-secured-integration.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
