---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: vault-sidecar-agent-injector
  name: vault-sidecar-agent-injector
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-secrets
  project: default
  source:
    path: 05-vault-sidecar-agent-injector
    repoURL: https://github.com/alvarolop/ocp-secured-integration.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
