---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-example
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: eso-example
    creationPolicy: Owner
    template:
      type: Opaque
  # data:
  #   - secretKey: demo1
  #     remoteRef:
  #       key: key1
  #       version: "1"
  dataFrom:
    - extract:
        key: "demo1"
