---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
  namespace: test-secrets
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    vault:
      server: "http://hashicorp-vault-server.vault.svc.cluster.local:8200"
      path: "secret/data"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "auth/kubernetes"
          role: "webapp"
