---
apiVersion: v1
kind: Secret
metadata:
  name: avp-backend-secret
  namespace: avp-gitops
stringData:
  # https://argocd-vault-plugin.readthedocs.io/en/stable/backends/#hashicorp-vault
  VAULT_ADDR: "http://hashicorp-vault-server.vault.svc.cluster.local:8200"
  AVP_TYPE: vault
  AVP_AUTH_TYPE: token
  VAULT_TOKEN: root
type: Opaque



